services:
  - type: web
    name: tg2-schedule-bot
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0